"""The Postgres checkpointer the claim graph compiles against -- [M4-09].

One module owns how the graph reaches Postgres, so ``build_claim_graph()`` stays
free of persistence concerns and the caller keeps owning ``.compile()``::

    with open_claim_checkpointer() as checkpointer:
        graph = build_claim_graph().compile(checkpointer=checkpointer)
        graph.invoke(state, config={"configurable": {"thread_id": claim_id}},
                     context=graph_context)

The checkpointer is not optional decoration: [M4-09]'s ``human_review`` node
calls ``interrupt()``, and an interrupt is only resumable when the state that
preceded it was written down. A graph compiled *without* a checkpointer does not
raise on ``interrupt()`` -- it returns early carrying ``__interrupt__`` and no
error -- so the failure mode of forgetting one is a silently truncated run, not
a crash. Every call site passes one.

Three things this module gets right that are easy to get wrong:

* **The URL.** The project's settings produce SQLAlchemy URLs
  (``postgresql+psycopg://``); psycopg rejects the ``+psycopg`` drivername.
  :func:`checkpointer_conn_string` converts via SQLAlchemy's own URL parser
  rather than string surgery.
* **The connection flags.** The LangGraph documentation requires
  ``autocommit=True`` (``setup()`` must commit its DDL) and
  ``row_factory=dict_row`` (the saver reads rows by key). ``prepare_threshold=0``
  matches what ``PostgresSaver.from_conn_string`` itself uses.
* **The serializer allowlist.** See :func:`build_checkpoint_serializer`.

Sync ``PostgresSaver``, not ``AsyncPostgresSaver``: the whole project is sync
psycopg3, a project-level decision recorded in ``docs/DATABASE.md``.
"""

from collections.abc import Iterator
from contextlib import contextmanager

from langgraph.checkpoint.postgres import PostgresSaver
from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer
from psycopg import Connection
from psycopg.rows import dict_row
from pydantic import BaseModel
from sqlalchemy.engine import make_url

from infrastructure.config.settings import DatabaseSettings
from infrastructure.graph import state as state_module

# Everything `PostgresSaver.setup()` creates. Alembic does not own these, and
# `alembic/env.py` filters them out of `--autogenerate` -- without that, the next
# autogenerated migration sees four tables in the database that are not in
# `Base.metadata` and emits a migration that DROPS them. See docs/DATABASE.md.
CHECKPOINTER_TABLES = frozenset(
    {
        "checkpoints",
        "checkpoint_blobs",
        "checkpoint_writes",
        "checkpoint_migrations",
    }
)

# The one probed by `assert_checkpointer_ready`, the way
# `assert_chunk_table_ready` probes `chunk`.
CHECKPOINT_TABLE = "checkpoints"

SETUP_COMMAND = "make setup-checkpointer"

# Enum types that reach graph state through the sub-models in `state.py`
# (`Citation.clause_type`, `CompatibilityAssessment.verdict`). They live in
# `domain`, so the enumeration below cannot find them.
_ENUM_TYPES: tuple[tuple[str, str], ...] = (
    ("domain.clause_classification", "ClauseType"),
    ("domain.verdict", "Verdict"),
)


def checkpointer_conn_string(sqlalchemy_database_url: str) -> str:
    """Turn a SQLAlchemy database URL into one psycopg accepts.

    ``postgresql+psycopg://user:pw@host/db`` -> ``postgresql://user:pw@host/db``.
    Parsed and re-rendered by SQLAlchemy rather than string-replaced, so a URL
    carrying query parameters, an IPv6 host or an escaped password survives
    intact. The password is rendered in the clear because it is going straight
    into a connection call -- never log the result.
    """
    return (
        make_url(sqlalchemy_database_url)
        .set(drivername="postgresql")
        .render_as_string(hide_password=False)
    )


def _state_model_types() -> tuple[tuple[str, str], ...]:
    """Every Pydantic model ``state.py`` defines, as ``(module, class name)``."""
    return tuple(
        (state_module.__name__, name)
        for name, value in vars(state_module).items()
        if isinstance(value, type)
        and issubclass(value, BaseModel)
        and value.__module__ == state_module.__name__
    )


def checkpoint_allowed_types() -> tuple[tuple[str, str], ...]:
    """The ``(module, class name)`` pairs the checkpoint serializer may rebuild."""
    return _state_model_types() + _ENUM_TYPES


def build_checkpoint_serializer() -> JsonPlusSerializer:
    """The serializer the checkpointer uses, with our state types allow-listed.

    LangGraph's msgpack serializer refuses to rebuild a type it was not told
    about, and -- this is the trap -- **it does not raise**: a blocked type comes
    back as a plain ``dict``, so a restored run would find ``state["recommendation"]``
    is a mapping rather than a ``Recommendation``, several nodes downstream. It
    also warns on every unregistered type when no allowlist is given, and the
    warning promises the permissive default will be removed.

    So the allowlist is explicit *and* derived: :func:`_state_model_types`
    enumerates the models ``state.py`` defines rather than repeating them here,
    which is what keeps a sub-model added by a later issue from silently
    degrading. Entries must be ``(module, class name)`` pairs -- a module-only
    entry matches nothing.
    ``tests/unit/infrastructure/graph/test_checkpointer.py`` round-trips a fully
    populated ``ClaimState`` and asserts every value keeps its type.
    """
    return JsonPlusSerializer(allowed_msgpack_modules=checkpoint_allowed_types())


def assert_checkpointer_ready(conn: Connection[dict[str, object]]) -> None:
    """Fail loudly with the fix command if the checkpointer tables are missing.

    The counterpart to ``chunk_repository.assert_chunk_table_ready``: the
    checkpointer's schema is created by its own ``setup()``, not by Alembic, so
    a database that has had ``make migrate`` run against it can still be missing
    these tables.
    """
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
            (CHECKPOINT_TABLE,),
        )
        if cursor.fetchone() is None:
            raise RuntimeError(
                f"LangGraph checkpointer table `{CHECKPOINT_TABLE}` not found. "
                f"Run `{SETUP_COMMAND}` (or "
                f"`DATABASE_URL=$TEST_DATABASE_URL {SETUP_COMMAND}` for the test "
                "database)."
            )


@contextmanager
def open_claim_checkpointer(
    database_url: str | None = None,
    *,
    setup: bool = False,
) -> Iterator[PostgresSaver]:
    """Open a ``PostgresSaver`` on the service database for the duration of a block.

    ``database_url`` accepts either flavour of URL and defaults to the same
    ``DatabaseSettings`` the rest of the service reads -- the checkpointer shares
    the application database, it does not get one of its own.

    ``setup=True`` runs the checkpointer's own migrations; only
    ``scripts/setup_checkpointer.py`` passes it, so there is one place that
    creates this schema, the way ``make migrate`` is the one place Alembic runs.
    Every other caller gets :func:`assert_checkpointer_ready` instead, which
    turns a missing schema into an actionable message rather than a psycopg
    ``UndefinedTable``.
    """
    resolved = database_url or DatabaseSettings().sqlalchemy_database_url
    with Connection.connect(
        checkpointer_conn_string(resolved),
        autocommit=True,
        prepare_threshold=0,
        row_factory=dict_row,
    ) as conn:
        checkpointer = PostgresSaver(conn, serde=build_checkpoint_serializer())
        if setup:
            checkpointer.setup()
        else:
            assert_checkpointer_ready(conn)
        yield checkpointer
