"""Markdown per-document chunking report -- [M3-01]."""

from collections.abc import Sequence
from dataclasses import dataclass


@dataclass(frozen=True)
class ChunkReportRow:
    """One document's chunking outcome, ready to render into the report table."""

    document_id: str
    filename: str
    clause_count: int
    chunk_count: int
    single_count: int
    merged_count: int
    item_boundary_split_count: int
    sliding_window_split_count: int
    min_char_count: int
    p50_char_count: int
    p90_char_count: int
    max_char_count: int


def render_chunk_report(rows: Sequence[ChunkReportRow]) -> str:
    """Render the Markdown chunking report."""
    lines = [
        "# Chunking report",
        "",
        "Generated by `scripts/build_chunks.py` over every document in "
        "`data/policies/manifest.csv`. Chunks the clause tree recovered by "
        "[M1-04] instead of fixed token windows: one chunk per leaf clause "
        "by default, short clauses merged into their parent, over-long "
        "clauses split on internal item boundaries with an overlapping "
        "sliding window only as the last resort.",
        "",
        "| Document | Filename | Clauses | Chunks | Single | Merged | "
        "Item-split | Window-split | Min len | p50 len | p90 len | Max len |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | "
        "---: |",
    ]
    for row in rows:
        lines.append(_render_row(row))

    total_chunks = sum(row.chunk_count for row in rows)
    total_single = sum(row.single_count for row in rows)
    total_merged = sum(row.merged_count for row in rows)
    total_item_split = sum(row.item_boundary_split_count for row in rows)
    total_window_split = sum(row.sliding_window_split_count for row in rows)

    lines += [
        "",
        "## Summary",
        "",
        f"- Total chunks: {total_chunks}",
        f"- Single (default, one clause -> one chunk): {total_single}",
        f"- Merged (short clause(s) folded into a parent): {total_merged}",
        f"- Item-boundary split: {total_item_split}",
        f"- Sliding-window split (last resort): {total_window_split}",
        f"- Documents: {len(rows)}.",
        "",
    ]
    return "\n".join(lines)


def _render_row(row: ChunkReportRow) -> str:
    """Render one document's report row."""
    return (
        f"| {row.document_id} | {row.filename} | {row.clause_count} | "
        f"{row.chunk_count} | {row.single_count} | {row.merged_count} | "
        f"{row.item_boundary_split_count} | {row.sliding_window_split_count} | "
        f"{row.min_char_count} | {row.p50_char_count} | {row.p90_char_count} | "
        f"{row.max_char_count} |"
    )
