"""Markdown per-document boilerplate-removal report."""

from collections.abc import Sequence
from dataclasses import dataclass


@dataclass(frozen=True)
class BoilerplateReportRow:
    """One document's removal outcome, ready to render into the report table."""

    document_id: str
    filename: str
    page_count: int
    header_footer_lines_removed: int
    toc_dot_leader_lines_removed: int
    toc_pages_removed: int
    toc_page_lines_removed: int
    marketing_pages_removed: int
    marketing_page_lines_removed: int
    total_chars_before: int
    total_chars_after: int
    removed_page_numbers: tuple[int, ...] = ()


def render_report(rows: Sequence[BoilerplateReportRow]) -> str:
    """Render the Markdown boilerplate-removal report."""
    lines = [
        "# Boilerplate removal report",
        "",
        "Generated by `scripts/remove_boilerplate.py` over every document in "
        "`data/policies/manifest.csv`. Reads the extraction "
        "cache, strips repeated headers/footers, table-of-contents lines and "
        "front-matter marketing/cover pages, and caches the result "
        "under `data/cache/boilerplate_removed/` for the clause-tree pass to "
        "consume. Removal counts are per-document and never aggregated away, "
        "so an outlier is visible here rather than silent.",
        "",
        "| Document | Filename | Pages | Header/footer lines | "
        "TOC dot-leader lines | TOC pages | TOC page lines | "
        "Marketing pages | Marketing page lines | Chars before | "
        "Chars after | Removed pages |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | "
        "---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(_render_row(row))

    total_header_footer = sum(row.header_footer_lines_removed for row in rows)
    total_toc_dot_leader = sum(row.toc_dot_leader_lines_removed for row in rows)
    total_toc_pages = sum(row.toc_pages_removed for row in rows)
    total_marketing_pages = sum(row.marketing_pages_removed for row in rows)
    total_chars_before = sum(row.total_chars_before for row in rows)
    total_chars_after = sum(row.total_chars_after for row in rows)
    docs_with_marketing_page = sum(1 for row in rows if row.marketing_pages_removed > 0)

    lines += [
        "",
        "## Summary",
        "",
        f"- Header/footer lines removed: {total_header_footer}",
        f"- TOC dot-leader lines removed: {total_toc_dot_leader}",
        f"- TOC pages removed: {total_toc_pages}",
        f"- Marketing/cover pages removed: {total_marketing_pages} "
        f"({docs_with_marketing_page}/{len(rows)} documents)",
        f"- Total characters: {total_chars_before} → {total_chars_after}",
        f"- Documents out of {len(rows)} total.",
        "",
    ]
    return "\n".join(lines)


def _render_row(row: BoilerplateReportRow) -> str:
    """Render one document's report row."""
    removed_pages = ", ".join(str(page) for page in row.removed_page_numbers) or "none"
    return (
        f"| {row.document_id} | {row.filename} | {row.page_count} | "
        f"{row.header_footer_lines_removed} | {row.toc_dot_leader_lines_removed} | "
        f"{row.toc_pages_removed} | {row.toc_page_lines_removed} | "
        f"{row.marketing_pages_removed} | {row.marketing_page_lines_removed} | "
        f"{row.total_chars_before} | {row.total_chars_after} | {removed_pages} |"
    )
