"""Markdown per-document clause-tree segmentation report."""

from collections.abc import Sequence
from dataclasses import dataclass


@dataclass(frozen=True)
class ClauseTreeReportRow:
    """One document's segmentation outcome, ready to render into the report table."""

    document_id: str
    filename: str
    page_count: int
    clause_count: int
    max_depth: int
    orphan_ratio: float
    extraction_mode: str
    warning_count: int
    exceeds_threshold: bool


def render_report(rows: Sequence[ClauseTreeReportRow], *, threshold: float) -> str:
    """Render the Markdown clause-tree segmentation report."""
    lines = [
        "# Clause tree report",
        "",
        "Generated by `scripts/build_clause_tree.py` over every document in "
        "`data/policies/manifest.csv`. Reads the boilerplate-removed "
        "cache, recovers a parent-referenced clause hierarchy from heading "
        "numbering, and caches the result under "
        "`data/cache/clause_trees/` for the classification pass to consume. "
        f"Orphan ratio is flagged (⚠) when it exceeds the configured threshold "
        f"({threshold:.2f}) rather than hidden.",
        "",
        "| Document | Filename | Pages | Clauses | Max depth | Orphan ratio | "
        "Mode | Warnings |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | ---: |",
    ]
    for row in rows:
        lines.append(_render_row(row))

    total_clauses = sum(row.clause_count for row in rows)
    exceeding = [row for row in rows if row.exceeds_threshold]
    exceeding_ids = ", ".join(row.document_id for row in exceeding)

    lines += [
        "",
        "## Summary",
        "",
        f"- Total clauses recovered: {total_clauses}",
        f"- Documents exceeding the orphan-ratio threshold: {len(exceeding)}"
        + (f" ({exceeding_ids})" if exceeding else ""),
        f"- Documents out of {len(rows)} total.",
        "",
    ]
    return "\n".join(lines)


def _render_row(row: ClauseTreeReportRow) -> str:
    """Render one document's report row."""
    marker = " ⚠" if row.exceeds_threshold else ""
    return (
        f"| {row.document_id} | {row.filename} | {row.page_count} | "
        f"{row.clause_count} | {row.max_depth} | {row.orphan_ratio:.3f}{marker} | "
        f"{row.extraction_mode} | {row.warning_count} |"
    )
