"""Markdown per-page character report for the extraction pipeline."""

from collections.abc import Sequence
from dataclasses import dataclass

from application.use_cases.extraction_policy import ExtractionRoute

_ROUTE_LABELS = {
    ExtractionRoute.EXTRACT_NOW: "extracted (text layer)",
    ExtractionRoute.OCR_REQUIRED: "extracted (OCR)",
}


@dataclass(frozen=True)
class ExtractionReportRow:
    """One document's outcome, ready to render into the report table."""

    document_id: str
    filename: str
    route: ExtractionRoute
    page_count: int | None = None
    total_chars: int | None = None
    avg_chars_per_page: float | None = None
    flagged_pages: tuple[int, ...] = ()


def render_report(rows: Sequence[ExtractionReportRow], threshold: int) -> str:
    """Render the Markdown extraction report."""
    lines = [
        "# Text extraction report",
        "",
        "Generated by `scripts/extract_text.py` over every document in "
        "`data/policies/manifest.csv`. Documents with no usable text layer "
        "are rasterized and OCR'd (Tesseract, see [M1-02]) instead of read "
        "from the PDF's text layer; both paths produce comparable per-page "
        "stats below.",
        "",
        f"- Low-character-page threshold: {threshold} extracted characters "
        "(`EXTRACTION_LOW_CHAR_PAGE_THRESHOLD`).",
        "",
        "| Document | Filename | Route | Pages | Total chars | "
        "Avg chars/page | Flagged pages |",
        "| --- | --- | --- | ---: | ---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(_render_row(row))

    extracted = [row for row in rows if row.route is ExtractionRoute.EXTRACT_NOW]
    ocr_routed = [row for row in rows if row.route is ExtractionRoute.OCR_REQUIRED]
    flagged_total = sum(len(row.flagged_pages) for row in rows)

    lines += [
        "",
        "## Summary",
        "",
        f"- Extracted from text layer: {len(extracted)}",
        f"- Extracted via OCR: {len(ocr_routed)}",
        f"- Documents out of {len(rows)} total.",
        f"- Flagged low-character pages across all documents: {flagged_total}",
        "",
    ]
    return "\n".join(lines)


def _render_row(row: ExtractionReportRow) -> str:
    """Render one document's report row."""
    flagged = ", ".join(str(page) for page in row.flagged_pages) or "none"
    avg = row.avg_chars_per_page if row.avg_chars_per_page is not None else 0.0
    return (
        f"| {row.document_id} | {row.filename} | {_ROUTE_LABELS[row.route]} | "
        f"{row.page_count} | {row.total_chars} | {avg:.1f} | {flagged} |"
    )
