"""Markdown per-page character report for the extraction pipeline."""

from collections.abc import Sequence
from dataclasses import dataclass

from application.use_cases.extraction_policy import ExtractionRoute


@dataclass(frozen=True)
class ExtractionReportRow:
    """One document's outcome, ready to render into the report table."""

    document_id: str
    filename: str
    route: ExtractionRoute
    page_count: int | None = None
    total_chars: int | None = None
    avg_chars_per_page: float | None = None
    flagged_pages: tuple[int, ...] = ()


def render_report(rows: Sequence[ExtractionReportRow], threshold: int) -> str:
    """Render the Markdown extraction report."""
    lines = [
        "# Text extraction report",
        "",
        "Generated by `scripts/extract_text.py` over every document in "
        "`data/policies/manifest.csv`. Documents routed to OCR are listed "
        "but not extracted here -- see [M1-02].",
        "",
        f"- Low-character-page threshold: {threshold} extracted characters "
        "(`EXTRACTION_LOW_CHAR_PAGE_THRESHOLD`).",
        "",
        "| Document | Filename | Route | Pages | Total chars | "
        "Avg chars/page | Flagged pages |",
        "| --- | --- | --- | ---: | ---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(_render_row(row))

    extracted = [row for row in rows if row.route is ExtractionRoute.EXTRACT_NOW]
    ocr_routed = [row for row in rows if row.route is ExtractionRoute.OCR_REQUIRED]
    flagged_total = sum(len(row.flagged_pages) for row in extracted)

    lines += [
        "",
        "## Summary",
        "",
        f"- Extracted now: {len(extracted)}",
        f"- Routed to OCR (not extracted, see M1-02): {len(ocr_routed)}",
        f"- Documents out of {len(rows)} total.",
        f"- Flagged low-character pages across all extracted documents: "
        f"{flagged_total}",
        "",
    ]
    return "\n".join(lines)


def _render_row(row: ExtractionReportRow) -> str:
    """Render one document's report row."""
    if row.route is ExtractionRoute.OCR_REQUIRED:
        return (
            f"| {row.document_id} | {row.filename} | ocr_required | - | - | "
            "- | routed to OCR, not extracted (see M1-02) |"
        )
    flagged = ", ".join(str(page) for page in row.flagged_pages) or "none"
    avg = row.avg_chars_per_page if row.avg_chars_per_page is not None else 0.0
    return (
        f"| {row.document_id} | {row.filename} | extracted | "
        f"{row.page_count} | {row.total_chars} | {avg:.1f} | {flagged} |"
    )
